name: Semantic Release
on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Semver

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
